baseURL = "https://iqbalpratama.netlify.app/"
languageCode = "en-us"
theme = "aafu"

[params]
    title = "Iqbal Pratama"
    author = "Iqbal Pratama"
    description = "Website title"
    copyright = ""

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = false
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Iqbal Pratama"
		tagline = "Job Seeker"
		location = "Yogyakarta, ID"
        photo = "iqball.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/iqbal-pratamaa/"
            title = "LinkedIn"		
        [[params.social.list]]
            class = "fab"
            icon = "fa-facebook"
            url = "https://www.facebook.com/profile.php?id=100033309741244"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/iqbalprtm"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-instagram"
            url = "https://www.instagram.com/iqbalpratama_98/"
            title = "instagram"
        [[params.social.list]]
            class = "fab"
            icon = "fa-whatsapp"
            url = "https://wa.link/ybqwe0"
            title = "wa"
        [[params.social.list]]
            class = "fab"
            icon = "fa-telegram"
            url = "https://t.me/iqbalpratama_98"
            title = "wa"
        
    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Hallo, nama saya Iqbal Pratama**, saya berpengalaman lebih dari 3 tahun di bidang Sales Marketing dan General Affair."

    # Experience section
    [params.experience]
        title = "Pengalaman"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Business Consultant"
            dates = "April 2020 - Sekarang"
	    link = "https://goo.gl/maps/iya2WXY2Bk6vupBr6"
            company = "PT. DIDIMAX BERJANGKA YOGYAKARTA"
            details = "Menerangkan kepada nasabah tentang bisnis trading forex"
        [[params.experience.list]]
            position = "Marketing"
            dates = "November 2019 - February 2020"
            link = "https://goo.gl/maps/6qhWvQ8mjW3Y8uvn6"
            company = "Kredit Plus"
	    details = "Mencari dan menawarkan credit kepada calon customer dan menjelaskan presedural pengajuan credit kepada customer"

        [[params.experience.list]]
            position = "General Affair"
            dates = "Agustus 2018 - Agustus 2019"
            link = "https://goo.gl/maps/FQbEtGpTs455R4uA7"
            company = "PT.Telmark Integrasi Indonesia"
	    details = "Inventory asset perusahaan setiap bulan dan menangani proses pemeliharaan bangunan operasional terutama sipil"
	    
    # Education section
    [params.education]
        title = "Pendidikan"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Otomotif"
            college = "SMK BERBUDI GANTIWARNO KLATEN JAWA TENGAH"
            dates = "2013 - 2018"
            thesis_title = "My School"
            thesis_link = "https://goo.gl/maps/XHdWkWgdJ1pnL48d9"

    # Publication section
    

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = ""
            

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Office Iventory"
            skillrating = 78
        [[params.skill.list]]
            skill = "Negotiation Skill"
            skillrating = 65
        [[params.skill.list]]
            skill = "Ms Office & AutoCAD"
            skillrating = 80
        [[params.skill.list]]
            skill = "Instalasi Listrik Gedung"
            skillrating = 78

        [[params.skill.list]]
            skill = "Tata Ruang Gedung"
            skillrating = 55

        [[params.skill.list]]
            skill = "Maintenace Gedung (Listrik, Air & Internet)"
            skillrating = 55


    # Hobby section
    [params.hobby]
        title = "Hobi"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Video Editing"

